#!/bin/sh
#
# bladekp 2016
#
# LITERATURA:
# https://wiki.freebsd.org/RootOnZFS/GPTZFSBoot 
# https://forums.freebsd.org/threads/zfs-boot-from-usb.45880/
#
# https://calomel.org/zfs_freebsd_root_install.html
# https://www.freebsd.org/doc/en/articles/remote-install/preparation.html
# http://louwrentius.com/freebsd-101-unattended-install-over-pxe-http-no-nfs.html
#
# vol:/usr/local/zetis/sbin/freebsd-devprep
# vol:/usr/local/zetis/sbin/freebsd-install
#
# na mfsBSD zetis 10.2-STABLE
#
# czas wykonywania około 3min
#
# przed wykonaniem skryptu skopiować jego zawartość do pliku, nadać plikowi prawa do wykonowania, wykonać
# po zakończeiu zresetować i uruchomić system z dysku lokalnego

echo "## START ##"

echo ""
echo "# kasuję poprzednie zapisy na dysku i zpoola #"
umount zroot
umount /mnt
zpool destroy zroot
gpart delete -i 2 da0
gpart delete -i 1 da0
gpart destroy -F da0

echo ""
echo "# tworzenie partycji bootstrap i zfs #"

gpart create -s gpt da0
gpart add -a 4k -s 64k -t freebsd-boot da0
gpart add -a 4k -t freebsd-zfs -l disk0 da0 						# na reszcie dysku zfs
gpart bootcode -b /boot/pmbr -p /boot/gptzfsboot -i 1 da0 	# wgrywamy kod bootstrap

echo ""
echo "# tworzenie poola #"
gnop create -S 4096 /dev/gpt/disk0		# sektory 4kB
zpool create -f -o altroot=/mnt -o cachefile=/var/tmp/zpool.cache zroot /dev/gpt/disk0.nop
zpool export zroot
gnop destroy /dev/gpt/disk0.nop
zpool import -o altroot=/mnt -o cachefile=/var/tmp/zpool.cache zroot

echo ""
echo "# ustawianie istotnych pól zfs-a #"
zpool set bootfs=zroot zroot
zpool set listsnapshots=on zroot
zpool set autoreplace=on zroot
zfs set checksum=fletcher4 zroot
zfs set compression=lz4 zroot
zfs set atime=off zroot
zfs set copies=2 zroot

echo ""
echo "# dodajemy swap #"
zfs create -V 1G zroot/swap
zfs set org.freebsd:swap=on zroot/swap

echo ""
echo "# link symboliczny do /home"
cd /mnt/zroot ; ln -s usr/home home

echo ""
echo "# Montowanie plików systemowych i instalacja systemu 2-3min #"

mkdir /cdrom
mount /ftp/pub
mdconfig -a -t vnode -u 9 -f /ftp/pub/FreeBSD/releases/ISO-IMAGES/10.2/FreeBSD-10.2-RELEASE-amd64-disc1.iso
mount_cd9660 /dev/md9 /cdrom

cd /cdrom/usr/freebsd-dist
export DESTDIR=/mnt/zroot

for file in base.txz kernel.txz doc.txz ports.txz src.txz; #opcjonalnie lib32.txz 
do (cat $file | tar --unlink -xpJf - -C ${DESTDIR:-/}); done

echo ""
echo "# kopiujemy zpool.cache na nowy dysk #"
cp /var/tmp/zpool.cache /mnt/zroot/boot/zfs/zpool.cache

echo ""
echo "# dodanie ładowania zfs na starcie do konfiguracji #"
echo 'zfs_enable="YES"' >> /mnt/zroot/etc/rc.conf
echo 'zfs_load="YES"' >> /mnt/zroot/boot/loader.conf
echo 'vfs.root.mountfrom="zfs:zroot"' >> /mnt/zroot/boot/loader.conf

echo ""
echo "# zmiana na gpt ids żeby ładnie wyglądały etykiety dysków https://forums.freebsd.org/threads/disk-labels.44612/ #"
echo 'kern.geom.label.disk_ident.enable="0"' >> /mnt/zroot/boot/loader.conf
echo 'kern.geom.label.gpt.enable="1"' >> /mnt/zroot/boot/loader.conf
echo 'kern.geom.label.gptid.enable="0"' >> /mnt/zroot/boot/loader.conf

echo ""
echo "# ustawienia sieci, ssh, syslog, etc. #"
echo 'hostname="bladekp"' >> /mnt/zroot/etc/rc.conf
echo 'ifconfig_em0="dhcp"' >> /mnt/zroot/etc/rc.conf
echo 'sshd_enable="YES"' >> /mnt/zroot/etc/rc.conf
echo 'syslogd_flags="-ss"' >> /mnt/zroot/etc/rc.conf

echo ""
echo "# dotykamy /etc/fstab inaczej freebsd nie wystartuje poprawnie https://forums.freebsd.org/threads/zfs-boot-from-usb.45880/ #"
touch /mnt/zroot/etc/fstab

sync
echo "# koniec, zresetuj maszynę i spróbuj zbootować z dysku #"
sync
